### ISSUE TITLE
0.1.0: Create basic Eclipse e4 application skeleton

### ISSUE THREAD

**Issue by sdruskat** [hexatomic/hexatomic#14]
Target: https://github.com/hexatomic/hexatomic/pull/13

- [x] Create Eclipse e4 skeleton app that can be built with Tycho, including multi-platform build artifacts and custom target platform
- [x] Add docs for auto-deployment to hexatomic.github.io/hexatomic (user + dev/maintainer docs)
- [x] Add CI support (testing on PRs (@thomaskrause to discuss where CI should kick in), building and deploying) via Travis
- [ ] Document

**Comment by thomaskrause** [comment]
>     * [ ]  Add CI support (testing on PRs (@thomaskrause to discuss where CI should kick in), building and deploying) via Travis

From what I see CI is already working on pull requests (e.g. #22) and produces meaningful feedback.

>     * [ ]  Automate deployment via CI
I think this should not be part of *this* particular PR since we can already build the product locally. Waiting for this PR to be merged is a major blocker for actual feature development, and automatic CI *deployment* is not needed for development, but only for release of a public product release. Even a source code release without automatic CI deployment could be possible.

**Comment by sdruskat** [comment]
Automated deployment via CI moved to #23.

**Comment by sdruskat** [comment]
Closing due to uselessness.
