### ISSUE TITLE
0.2.0 Let Salt, Pepper, graphANNIS provide their own p2 builds

### ISSUE THREAD

**Issue by sdruskat** [hexatomic/hexatomic#15]
I think that this is how Salt, Pepper, graphANNIS should be provided for consumption in Hexatomic: All three projects build p2 artifacts in CI and deploy to a korpling p2 repo on korpling.org.

TODOs (incomplete):
- [X] Investigate strategy for p2 repo setup that can keep arbitrary numbers of versions, possibly through dir structure (automated deploys via version var-replacement in builds)
- [x] Set up p2-ifier build step for Salt -> https://korpling.github.io/salt/p2/develop/
- [x] Set up p2-ifier build step for Pepper -> https://korpling.github.io/graphANNIS-java/p2/develop/
- [x] Set up p2-ifier build step for graphANNIS -> https://korpling.github.io/graphANNIS-java/p2/develop/
- [x] Document (in respective projects, not in Hexatomic)
- [x] Test integration in Hexatomic
- [ ] Skip unneeded dependencies via .tpd (otherwise, duplicate dependencies from both Hexatomic & Salt/Pepper will break target platform resolution)

**Comment by sdruskat** [comment]
@thomaskrause Feel free to get going with this at your convenience, or discuss here if you think this isn't viable. I think architecturally this is the cleanest option by far.

**Comment by thomaskrause** [comment]
We decided to go for GitHub pages for now, to not introduce another dependency to an internal service (including all the authorization management). There will be a P2 repository for each of the projects and each minor version. We might want to remove old and used versions from the gh-pages branches if we reach any GitHub quota.

**Comment by thomaskrause** [comment]
The pepper P2 repo (https://korpling.github.io/graphANNIS-java/p2/develop/) also contains Salt, because it is a fixed dependency. Maybe we should not add the Salt P2 repository but rely on Pepper instead. This would also help to avoid Salt version conflicts. On the downside, every Salt release we want to use in Hexatomic would need to trigger a Pepper release.

**Comment by sdruskat** [comment]
> Maybe we should not add the Salt P2 repository but rely on Pepper instead. This would also help to avoid Salt version conflicts. On the downside, every Salt release we want to use in Hexatomic would need to trigger a Pepper release.

Re this, it might be an option to just use Pepper, agreed.

Based on our discussions, am I right in assuming that

1. The current Salt and Pepper combination will not be incremented much further, but that the future may see a new implementation based on, e.g., graphANNIS?
2. It is the dev strategy for Pepper lib to include the latest possible Salt version?

In the past, I've had periods when I was developing against a local SNAPSHOT of Salt because the dev workflow for Salt was stuck and I couldn't get my necessary changes in quick enough (showstopper). I think that we are in a good position to avoid these things at the moment, due to the Hexatomic project and close collab.

So as long as we can ensure that changes to Salt which may prove necessary for Hexatomic can get implemented and pulled into a release fairly quickly, I don't mind doing it this way and avoiding unnecessary complexity.

**Comment by thomaskrause** [comment]
>     1. The current Salt and Pepper combination will not be incremented much further, but that the future may see a new implementation based on, e.g., graphANNIS?
>
Yes, there will be probably bug-fixes and smaller convenience features but not a major Salt 4 release soon. Pepper will need fixes with its parallelization and maybe some other internal refactoring, but not larger features (however, the modules/plugins however might change a lot)
>     2. It is the dev strategy for Pepper lib to include the latest possible Salt version?

Salt is *the* basic dependency of Pepper and must be included. Since we will use Pepper only for imports and exports via the pepper-lib API, it might be feasible to have both the salt-api and pepper-lib as dependencies. In this case we have to make sure Pepper is not exporting any Salt packages in its Manifest.

> In the past, I've had periods when I was developing against a local SNAPSHOT of Salt because the dev workflow for Salt was stuck and I couldn't get my necessary changes in quick enough (showstopper). I think that we are in a good position to avoid these things at the moment, due to the Hexatomic project and close collab.
> 
> So as long as we can ensure that changes to Salt which may prove necessary for Hexatomic can get implemented and pulled into a release fairly quickly, I don't mind doing it this way and avoiding unnecessary complexity.

I think we should not remove the Salt P2 repo creation in the release process of Salt. If there is a Showstopper we can then either switch to the Salt P2 repo for the Salt dependency or decide to update Pepper, too.
