### ISSUE TITLE
Relations between the same elements are drawn on top of each other and are not disinguished by labels

### ISSUE THREAD

**Issue by sdruskat** [hexatomic/hexatomic#154]
**Describe the bug**

When creating more than one (here: pointing) relation between the same elements (here: structures), the two relations are drawn on top of each other, making them indistinguishable.

**To reproduce the bug**
1. Open a doc in the example corpus
2. Do `e #structure3 -> #structure5`
3. Do `e #structure3 -> #structure5` again

**Expected behavior**

1. The edges are not drawn on top of each other but fanned (similar to relations connecting the same nodes but in different directions).
2. The edges are distinguished by getting a label, similar to nodes.

**Screenshots**

![image](https://user-images.githubusercontent.com/3007126/75028421-80c33a00-54a0-11ea-93e3-dfdce20c9f9d.png)

**Additional context**

Arguably a corner case, but something we should cover as you never know what users will do, e.g., using different edges to accumulate several annotations.

**Comment by thomaskrause** [comment]
This will be fixed by #160 

What happened was, that no new edge was actually created because of the existing edge. When #160 is merged, the example would look like this:

![grafik](https://user-images.githubusercontent.com/2168104/78545790-ae6c0480-77fc-11ea-84d1-6843b652a840.png)

I would argue that whether we need labels on the edges is a different discussion. Especially since it is also a quite philosophical discussion if we need to be able to distinguish two identical edges with identical annotations.
