### ISSUE TITLE
Can not input Chinese characters

### ISSUE THREAD

**Issue by fishfree** [hexatomic/hexatomic#261]
When I input:
t 这 是 一个 例子 。
An error occurs as the screenshot:
![image](https://user-images.githubusercontent.com/1741341/105928258-91047180-6080-11eb-9cbd-2bd786fc12b9.png)

I'm afraid the problem also exists for Japanese/Korean.

**Comment by sdruskat** [comment]
Thanks very much for reporting this, and sorry for the delay in replying!

Can you tell me the Unicode code point for the last character `。` please? I can get `t 这 是 一个 例子` to work in an experimental bug fix adding a range of `\u4E00-\u9FFF` to the parser, but the last character doesn't seem to be included.

![cn](https://user-images.githubusercontent.com/3007126/109058662-9090e200-76e3-11eb-996a-14652c89fb86.gif)

@thomaskrause: Not sure I read the ANTLR4 lexer rules correctly, but I think `IDENTIFIER` seems to be the culprit:

https://github.com/hexatomic/hexatomic/blob/c3417a019bef0b89ebe0def742d0d5ffacae494a/bundles/org.corpus_tools.hexatomic.graph/src/main/antlr4/org/corpus_tools/hexatomic/console/ConsoleLexer.g4#L20

I can get the behaviour in the gif by adding unicode ranges (`IDENTIFIER: ([a-zA-Z0-9_'\u4E00-\u9FFF'])+;`), but I think `IDENTIFIER` has multiple purposes, i.e., is used for Salt identifiers as well as token text, right? In this case I guess it'd be good to disambiguate it and use a `TOKEN` rule which includes different unicode ranges.

**Comment by thomaskrause** [comment]
Can you try if  ` t "这" "是" "一个" "例子" "。"` (with quotes around the token strings) works? For non-quoted strings we need to make some assumptions about what are valid characters to avoid clashes with other operators or keywords or whitespace characters (from which there are many kinds). That makes it difficult to extend the valid character set because there might be a clash in the future, and we should be more conservative in what we allow

**Comment by thomaskrause** [comment]
> I can get the behaviour in the gif by adding unicode ranges (`IDENTIFIER: ([a-zA-Z0-9_'\u4E00-\u9FFF'])+;`), but I think `IDENTIFIER` has multiple purposes, i.e., is used for Salt identifiers as well as token text, right? In this case I guess it'd be good to disambiguate it and use a `TOKEN` rule which includes different unicode ranges.

Yes, if we extend the character range we should distinguish between `IDENTIFIER` and `TOKEN`. `TOKEN` could be something like "non-whitespace and non-quotation character".

**Comment by thomaskrause** [comment]
> I can get the behaviour in the gif by adding unicode ranges (IDENTIFIER: ([a-zA-Z0-9_'\u4E00-\u9FFF'])+;), but I think IDENTIFIER has multiple purposes, i.e., is used for Salt identifiers as well as token text, right? In this case I guess it'd be good to disambiguate it and use a TOKEN rule which includes different unicode ranges.

The identifier is used for the Salt identifiers, but was more restrictively defined than necessary. In general, node identifiers will end up as the fragment part of the node URI, which can be any character except `#`. The definition here is from the ANNIS query language identifier definition, which is much more restrictive. Since we only should worry about Salt and the graph editor query language, extending this to all letter characters (according to the Unicode property) should be fine. We still must make sure the tokens of the lexer are unambiguous, but since the other special characters (`#`, `-` etc.) are not letter characters, this should be ok. I started a hotfix branch for this issue.
