### ISSUE TITLE
Hexatomic Beta 0.5.0 Release not running on Mac

### ISSUE THREAD

**Issue by sylvainloiseau** [hexatomic/hexatomic#271]
**Describe the bug**

The Hexatomic Beta 0.5.0 Release does not run on Mac.

**To reproduce the bug**

Download and run the release

**Screenshots**

![Capture d’écran 2021-03-05 à 11 51 47](https://user-images.githubusercontent.com/35781247/110105839-2d6d1280-7da9-11eb-9c59-39a3700e1682.png)

(Sorry, it says: "Hexatomic" is damaged and cannot be opened.")

It looks like the file isn't complete.

**Desktop (please complete the following information):**

 - Operating System: macos 10.15.7
 - Hexatomic Version: release 0.5.0 Beta
 - Java Version: openjdk 11.0.9

**Additional context**

The previous release wasn't running either (it's not a regression).

I can run Hexatomic on Mac, through the sources, generating the target platform and creating a debug configuration.

**Comment by thomaskrause** [comment]
Thanks for the bug report, I can reproduce it with macOS 11.1. This might a permission problem, since when I open a terminal, change into the directory where it was automatically unpacked after the download and and execute `./Contents/MacOS/hexatomic` in the terminal directly it works. I assume most macOS users of open source research software already know how to work around the "unsafe application" warnings were the developer signature is missing, but this error is different.

**Comment by thomaskrause** [comment]
So, this is related to the application quarantine. If you remove the corresponding attribute on the terminal, Hexatomic will start normally:
```
xattr -d com.apple.quarantine hexatomic.app/
```
I'm not a macOS user, but I thought for quarantined apps there should be a warning dialog like "This was downloaded from the Internet, do you really want to execute it?" message and the possibility to run it anyway. We should check if there are some original signatures or mismatches in the application metadata that causes this quarantine check to fail completely.

**Comment by sylvainloiseau** [comment]
Ok, thanks a lot. However I think there is something weird, normally macos do show a warning dialog "This was downloaded from the internet..." ; here the message is misleading ("Hexanomic is corrupted"). Anyway, thanks for a stunning app. I hope it will be developed further as it deserves.

**Comment by thomaskrause** [comment]
I did some further research and indeed this is quite unexpected behavior we need to fix in our build. From what I gathered so far, Eclipse Tycho downloads an already signed binary file (signed from the Eclipse cooperation) and bundles everything into "hexatomic.app". While the binary is signed, the other resources don't match any more and this is worse than not being signed at all because macOS assumes the app is broken. I manually signed the app with a self-signed certificate, which shows the expected behavior. There seem to be two options to go forward

a) further investigate if there is a way to use the pre-signed Eclipse executable
b) build the macOS packages on a macOS virtual machine in Github Actions and manually sign the result with a self-signed certificate (which will show the error, but at least allow execution).

@sdruskat What do you think about the issue?

**Comment by thomaskrause** [comment]
@sdruskat After some more investigation, I would vote for option b). If we execute

```bash
codesign --remove-signature hexatomic.app
```
in the build process **and the app is moved to Applications** after the download, the first time it is opened the following, actually ok dialog is presented:

![grafik](https://user-images.githubusercontent.com/2168104/110457880-6835ba00-80cb-11eb-8db0-aaa769101058.png)

This only comes once and is not so frightening. It is important to move the app out of the Download folder because additional quarantine settings will use a temporary read-only workspace and Hexatomic won't start. The installation instructions for macOS would need to be updated, but this seems like a reasonable easy way to do. I would try a PR that would execute the command in as a separate Job on macOS (because we need the `codesign` utility which is not available on Linux) and also updates the documentation.
