### ISSUE TITLE
Update does not work

### ISSUE THREAD

**Issue by reckart** [hexatomic/hexatomic#415]
**Describe the bug**
Update does not work. Just produces an unhelpful dialog.,

**To reproduce the bug**
1. Click on Help -> Update
2. See dialog

**Expected behavior**
Display if updates are available and allow installing them.

**Screenshots**
<img width="590" alt="Screenshot 2022-10-11 at 11 04 44" src="https://user-images.githubusercontent.com/1410238/195054974-bdff152e-f3b6-4d9a-b6db-0aa9d0f5ad76.png">

**Desktop (please complete the following information):**
 - Operating System: MacOS 12.6
 - Hexatomic Version: 1.0.1

**Comment by thomaskrause** [comment]
In the #418 pull request, we also improved the logic when this message is shown and there have been some cases where it could be shown, even when we did know for certain that there are no updates available.

Do you remember if there was anything "special" about the network situation (e.g. from a mobile hotspot or behind a firewall) when you did the tests? We also try to find better ways to debug the issues on macOS, in case this is related to some sand-boxing behavior.

**Comment by reckart** [comment]
I use a personal firewall that alerts me of all outgoing and incoming connections so I can approve or deny them.

**Comment by thomaskrause** [comment]
We resolved several issues in the update process, and it should work better on macOS from Hexatomic 1.1.7 onward. It should not show an annoying and confusing message if the automatic update check failed. From Hexatomic 1.2.0 onward, the automatic update check must be explicitly enabled.

@reckart Can you test if these fixes resolve your issue by
1. Download and install Hexatomic 1.1.7 (including moving the downloaded app to the Applications folder and enabling its execution)
2. Restarting Hexatomic once after a security exception was granted (the update check will fail on the first start, which is a known issue, but since the check will work at the next startup, this should not be a show-stopper)
3. Checking that an update is available and that installing the update works.

This should update from 1.1.7 to 1.2.0 and on the first start of 1.2.0, Hexatomic should ask for an explicit approval whether automatic updates checks should be allowed.

**Comment by thomaskrause** [comment]
We added more stabilizing behavior to the update process (like providing the complete Eclipse Product in our update site to be independent of external update sites).

If this issue still persists, please reopen this issue.
