### ISSUE TITLE
Implement save project functionality (with status indicator)

### ISSUE THREAD

**Issue by sdruskat** [hexatomic/hexatomic#93]
Implement global save project functionality, possibly via Action.
This includes setting DIRTY states for editors.

**Comment by thomaskrause** [comment]
We need to decide if we want to support saving single documents only. Saving the whole project would be a single command and aligned with the concept to open a project. 
Since this is the only way to save the corpus structure, we definitely need a "Save Project". 

But if we additionally allow to save only a changed document, we would need to make sure the user understands the difference.
This difference is also important for the status indicators: if every editor has its own status indicator the "Save Project" might seem insufficient for the user, since he expects to be able to save only this changes but not the one of other, possible hidden editors.

**Comment by sdruskat** [comment]
Good point. I think document-only saves support user stories. Can we do this incrementally?

1. Implement global "Save project" (and let user know about the implications in the docs)
2. Additionally implement "Save document" as "save editor contents", document implications; not sure if this is feasible due to binary (?) dirty states?

Alternatively, we could perhaps implement "Save Project" as an active action on the corpus structure view only, and "Save document" only on editor views?
